experiment:
  name: detr_resnet101_dc5_single_slice
  test: False
  resume: True

trainer: 
  _target_: pytorch_lightning.Trainer
  fast_dev_run: False
  gpus: 1
  max_epochs: 1000
  # overfit_batches: 4
  limit_train_batches: 100
  limit_val_batches: 10 
  limit_test_batches: 50
  num_sanity_val_steps: 1
  # profiler: simple

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ./checkpoints/${experiment.name}/
  filename: "{epoch}-{validation_loss:.3f}"
  monitor: validation_loss
  mode: min
  save_top_k: 3
  
hparams: 
  lr: 0.001 
  lr_backbone: 0.001 
  lr_transformer: 0.001 
  weight_decay: 0.0001

model: 
  _target_: hubconf.detr_resnet101_dc5
  num_classes: 91
  pretrained: True
  return_postprocessor: True

datamodule:
  _target_: datasets.oai.SegmentedKMRIOAIv00
  batch_size: 8
  num_workers: 6 

matcher: 
  _target_: models.matcher.HungarianMatcher
  cost_class: 1 
  cost_bbox: 2 
  cost_giou: 2   

criterion: 
  _target_: models.detr.SetCriterion
  num_classes: ${model.num_classes}
  losses: 
    - labels 
    - boxes 
    # - cardinality 
  eos_coef: 0.10
  weight_dict: 
    loss_ce: 1 
    loss_bbox: 5 
    loss_giou: 2 
